### ISSUE TITLE
Issue - "Close and Edit Icons Missing" (Internet Explorer) 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#10]
I then went back to see if I might of missed doing the roles the pen and X were not there so I could not edit

![edit](https://cloud.githubusercontent.com/assets/25959809/25594455/7de09296-2e75-11e7-8b0f-011cca46f3fb.png)

Guy Trimarchi, CSA III
Los Angeles DCFS

**Comment by JeffDent** [comment]
This appears to be corrected in latest version of sandbox. Confirmed on this date.
