### ISSUE TITLE
Issue - "Screening Name"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#11]
Title of screening did not change to reflect the name I had entered even after saving and submitting the screening. 

![srn name](https://cloud.githubusercontent.com/assets/25959809/25594569/f3e46ddc-2e75-11e7-9603-242adb5b61df.jpg)

Priscilla Chan
Los Angeles DCFS

**Comment by JeffDent** [comment]
UX story developed to answer this question.

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
