### ISSUE TITLE
Issue - "Screening Date/Time"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#12]
Report dates are not matching. The report date on the homepage showing my “caseloads” displays 4/15/17. However, the actual report/screening date I entered was 04/16/17.

![date1](https://cloud.githubusercontent.com/assets/25959809/25594634/44c7b5e2-2e76-11e7-87b1-beaaa974cf39.jpg)
![date2](https://cloud.githubusercontent.com/assets/25959809/25594636/456bb66a-2e76-11e7-9829-3f6b73e933f5.jpg)

Priscilla Chan
Los Angeles, DCFS

**Comment by JeffDent** [comment]
New bug story added https://www.pivotaltracker.com/story/show/145086357
