### ISSUE TITLE
Issue - “Create a New Person”

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#13]
Unable to click on the “Create a New Person” button. Every time I click it, it jumps to the top of the search bar. In the search bar, I searched for “Hannah Ernser”. Since the person does not exist, I scrolled to the bottom of the search results list and clicked on the “Create a new person” button. Once I click the button, it brings me back to the top.

![create](https://cloud.githubusercontent.com/assets/25959809/25594703/964628a4-2e76-11e7-97e3-fe692a3581eb.jpg)

Priscilla Chan
Los Angeles DCFS

**Comment by JeffDent** [comment]
Email to Priscilla to f/u on this issue 5/8/17 to specify browser and if the error is still happening

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17. Per Priscilla, this is no longer happening.
