### ISSUE TITLE
Feedback - "Date and Time"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#14]
I’m assuming in the future dates will be prepopulated to the system date and time. Currently, dates are not validated. System allows screening start time to be at a later date than end time. 

![date3](https://cloud.githubusercontent.com/assets/25959809/25594746/c8980afc-2e76-11e7-8efa-f31326f8f330.jpg)

Priscilla Chan
Los Angeles DCFS

**Comment by JeffDent** [comment]
This will be addressed in the following story-https://www.pivotaltracker.com/story/show/142862211

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
