### ISSUE TITLE
Feedback - "Allegations Selection"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#15]
It was difficult to select the allegations. It appears that the drop down menu is hidden.

![allegations2 png](https://cloud.githubusercontent.com/assets/25959809/25594802/0e5a3768-2e77-11e7-837d-6fec93fb1754.jpg)

Priscilla Chan
Los Angeles DCFS

**Comment by monte-williams** [comment]
This issue has been reported to occur in all 3 browsers.

**Comment by monte-williams** [comment]
Will we have the ability to see all the options at once?

Nataska Mohair
Fresno County

**Comment by JeffDent** [comment]
Viewing of allegations will be covered in this story-https://www.pivotaltracker.com/story/show/143194557

**Comment by pierreOSI** [comment]
@monte-williams This has been resolved!

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
