### ISSUE TITLE
Issue - Allegations - "Unable to assign" 2

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#16]
I created a referral for a safely surrendered child   SAFE SURRENDER - B8MAX8 and when I tried to create an allegation I was not able to.  As you can see the child’s name Baby Boy did not appear even thought I identified his role as victim.

![allegations3](https://cloud.githubusercontent.com/assets/25959809/25595098/62702f28-2e78-11e7-9295-46e6990e73b6.png)
![allegations4](https://cloud.githubusercontent.com/assets/25959809/25595097/6245e36c-2e78-11e7-87ac-b32cc6f89b69.png)

Guy Trimarchi
Los Angeles DCFS

**Comment by JeffDent** [comment]
Addressed in follow up email, where a perp was added to the screening and fixed this issue.
