### ISSUE TITLE
Issue - Yolo and Butte Network Connectivity

### ISSUE THREAD

**Issue by jcsimko** [ca-cwds/Sandbox#18]
## Issue Description

Yolo and Butte core county users are having network connectivity issues when trying to access the Sandbox website https://sandbox.cwds.ca.gov/

## Business Impact

Impacts ability of Yolo and Butte core county users from using the Sandbox. 

## Date/Time of first occurrence

First reported on 2017-03-16

## Is the Issue Repeatable?

Yes

**Comment by jcsimko** [comment]
Going to use remote desktop to validate Yolo connection on 5/1/17, AT&T is scheduled to make firewall changes 5/2/17.   If the firewall changes are made in the morning, CWS-NS staff plan to go out in the afternoon, otherwise they will do a site visit on Wednesday.

**Comment by jcsimko** [comment]
@ca-cwds/devops-eng - I know that you are working on this, but can you please provide updates here.

**Comment by david-sanabria** [comment]
@jcsimko This issue has been added to the DevOps backlog in bug story #144737337
https://www.pivotaltracker.com/story/show/144737337. It is actively being diagnosed, additional firewall rules and changes were identified today that will be implemented tomorrow. The current goal is to have network connectivity 100% operational for these counties by Thursday.

**Comment by jcsimko** [comment]
5/2/17 - As of this morning's Intake Core County Meeting, Oroville is able to connect, but Chico is not.  Yolo is also still unable to connect to the Sandbox.  @michaelsampath stat that both Chico and Yolo network connectivity to Sandbox should be resolved by tomorrow (5/3/17).

**Comment by jcsimko** [comment]
5/4/17 - All core counties are connected to both production and sandbox, except Chico (Butte). Chico is able to connect to production and not sandbox. We will have an update by tomorrow.

**Comment by jcsimko** [comment]
5/5/17 - Chico is now able to connect to Sandbox.
