### ISSUE TITLE
Feedback - "Roles" 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#19]
I have a question .  When identifying the roles of people I thought once you saved that person their role would display.  I have noticed this is not the case.  So is the role supposed to display or not.  My wish is that if it currently does not display is that it should display.  Here is a screen shot of a referral someone else did that I looked at and one I did

Guy Trimarchi
Los Angeles County

![roles1](https://cloud.githubusercontent.com/assets/25959809/25721887/e625a4c4-30c6-11e7-88eb-134ad18f49db.png)
![roles2](https://cloud.githubusercontent.com/assets/25959809/25721888/e626ba30-30c6-11e7-8165-3891e4f6f5ee.png)

**Comment by JeffDent** [comment]
Role is visible in show mode-https://www.pivotaltracker.com/story/show/143341023

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
