### ISSUE TITLE
Feedback - "UI" 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#20]
The light gray lines are confusing.  For example, on the people search, I would not have the light gray line directly under the person’s name, because when you add a second person, at first glance it looks like the information above the second person’s name is connected to the second person, when in reality it is connected to the first person. See below…
![ui](https://cloud.githubusercontent.com/assets/25959809/25721978/4013830c-30c7-11e7-9dee-1845ee0b551a.jpg)

•	When I add a person, it goes to the bottom of the list.  I think new people added should go to the top.  
•	Once I click save on a person, their role type does not appear any longer, which makes it so that I have to go back into the edit to make sure I didn’t accidentally click a wrong button. This actually happens pretty easily at this point, as it is still adding victim if you use the tab button after you’ve entered a different role category.  I think it should show along with their name, dob. S.S. and gender.
•	I agree with the earlier comments about the allegation being difficult to see at this point.

Wendy Vazquez
Butte County

**Comment by JeffDent** [comment]
Person that are added go the top-Bug Story https://www.pivotaltracker.com/story/show/143468011
Role visible in show mode-https://www.pivotaltracker.com/story/show/143341023

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.

**Comment by monte-williams** [comment]
The color (lack of contrast) was not addressed. Could you please state what will be done (if anything) regarding coloring of the page.
