### ISSUE TITLE
Issue - "UI" - Date/Time (IE & Chrome)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#21]
I have noticed this several times.   I have done a hand full of referrals today and the date of the referral changes after I submit it.  Here is a screen shot of the first card after I saved this card and before I submit the referral.  The date is 5/1/2017 (Info Call 2-O0WUNW)
![dt1](https://cloud.githubusercontent.com/assets/25959809/25722264/61096490-30c8-11e7-84e8-d072acaabaa2.png)

Here is the screen shot after I submitted it and then went back and opened it the sane referral the date now says 1/5/2017
![dt2](https://cloud.githubusercontent.com/assets/25959809/25722295/83e685ce-30c8-11e7-8d29-7e4508ff2301.png)

I did one variation on Chrome, rather than using the drop down calendar I typed in the date and found that the date did not change in chrome when the date is manually typed in.  the date dose change on the home page under report date still

Guy Trimarchi
Los Angeles County

**Comment by JeffDent** [comment]
This issue should be fixed with a browser agnostic date and time picker.

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
