### ISSUE TITLE
Issue - "Search" - Must type slowly

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#22]
..."Search it was a tad slow and still have to type slowly"

Guy Trimarchi
Los Angeles County

**Comment by JeffDent** [comment]
There is a story in the icebox to address this story. https://www.pivotaltracker.com/story/show/145068351

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log. Was reviewed with counties on 6/1/17.
