### ISSUE TITLE
Feedback - "Screening Name"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#24]
It’s not intuitive what to put here , is it the name of the person?

Louis Cretaro
Child Welfare Digital Services
County Consultant

**Comment by JeffDent** [comment]
We are in the process of completing usability testing on this and many other fields in the cards for the screening workflow

**Comment by monte-williams** [comment]
Screener name field is still unclear. Could you please provide more detail such as (same as County's Referral Name). @JeffDent 

Submitted by the County Consultants.
