### ISSUE TITLE
Feedback - "Demographics"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#29]
...the major parts that are missing are the language and race.

Nataska Mohair - Fresno County

**Comment by pierreOSI** [comment]
@monte-williams Language has been added, there is a story for race & latino origin: https://www.pivotaltracker.com/story/show/138532575

**Comment by kforderer** [comment]
Language is done: https://www.pivotaltracker.com/story/show/138383687
Race: https://www.pivotaltracker.com/story/show/138532575                   https://www.pivotaltracker.com/story/show/138532695
https://www.pivotaltracker.com/story/show/134813999

(NOTE: primary vs secondary language still needs some design work https://www.pivotaltracker.com/n/projects/1655887)

Added to Core County Feedback and Question Log and reviewed during meeting on 6/1/17.
