### ISSUE TITLE
Issue - Sandbox Performance Issues

### ISSUE THREAD

**Issue by jcsimko** [ca-cwds/Sandbox#3]
## Issue Description

At times, the Sandbox environment is very slow.  Different actions (e.g., "Search name", "Save Role", "Save Cross Report") can take up to 30-45 seconds to complete.

## Business Impact

Impacts ability to do user testing.

## Date/Time of first occurrence

First reported on 2017-04-27

## Is the Issue Repeatable?

Not consistently.

**Comment by jcsimko** [comment]
@ca-cwds/devops-eng - Please look into this.

**Comment by chadbratton** [comment]
Bug Story has been added: https://www.pivotaltracker.com/story/show/144724705

**Comment by jcsimko** [comment]
Developers are still exploring potential causes for performance issues.  They will be installing a tool that will allow for better diagnosis.
