### ISSUE TITLE
Feedback - "Location of Incident" 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#30]
I noticed that addresses have to be entered two times.  

An address is first entered when person is created. An address is again entered at location incident occurred.  There is drop down to report if incident occurred at Victim’s, home, school, etc,…but it appears the user also has to type address.  Is there a plan for address to autofill once a specific field is checked?   

Also, I did not see Alleged Perpetrator as an option for where incident occurred.  

Lindsay Ellington - Butte County

**Comment by JeffDent** [comment]
Address Validation has been pushed out of this Program Increment. Users will have to type duplicate addresses for a little while, until PI-4https://www.pivotaltracker.com/story/show/145765611
