### ISSUE TITLE
Issue - "Allegations" on Additional Entry(ies) (IE) (Chrome)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#31]
I was creating a referral in IE and I have a referral with two kids.  I was able to see the drop down of allegations and  selected an allegation for the first child  when I tried to do it for the second child the allegations were not visible. (LA Referral 06012017 - OK3Z8K    Promote to referral	01/05/2017)

![a](https://cloud.githubusercontent.com/assets/25959809/26705907/216d4090-46ee-11e7-8b8e-9f78cf575f83.png)

Guy Trimarchi, 
Los Angeles County

**Comment by monte-williams** [comment]
I tried to do a second referral with 2 victims again and this time I decided to select allegations for the second child first and the same thing happened   LA Referral 06012017 2 - FILH5L 

Guy Trimarchi,
 Los Angeles County

**Comment by monte-williams** [comment]
I went to look at the referral and edit the allegations. Yes, the drop down did not show up. I also found it difficult when the drop down came up. Only two allegations show up at a time. The down arrow for the drop down menu does not show up either. 

Tim Garcia, 
Butte County

**Comment by monte-williams** [comment]
Yes me as well.  I also tried this with google chrome  and the same thing occurred

Guy Trimarchi
Los Angeles County

**Comment by JeffDent** [comment]
The latest deployment of code has not pushed to the sandbox at this time. Updates to the sandbox will be coming soon.
