### ISSUE TITLE
Feedback - "Roles" 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#33]
Under Roles:
a. Can we add where the mandated reporter is from, school law enforcement?
b. Will options under role when creating people be expanded to include parent, other members?

Need ability to click a button for “anonymous” reporter rather than having to search anonymous; Need ability to just go straight to “anonymous”.

Submitted by the County Consultants

**Comment by JeffDent** [comment]
reporter information is being reexamined by UX team https://www.pivotaltracker.com/story/show/148040455
