### ISSUE TITLE
Feedback - "Roles" - Formatting

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#34]
Zip code field allows alphabet letters.

In SS#, there should be spaces with dashes in between; numbers don’t separate out.

Submitted by the County Consultants

**Comment by kforderer** [comment]
There is field validation/error messaging planned for SSN field: https://www.pivotaltracker.com/story/show/145703931

For zip, address standardization should resolve this issue. 

This item has been added to the feedback spreadsheet reviewed with core counties during Intake calls.
