### ISSUE TITLE
Feedback - " 'Person's' Card"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#35]
Would help to see title of role without having to click on client field edit. A Title of role relationship identified would be helpful. For example, below, there is no role title discerning that Janine is the victim and Mary A. is the perpetrator, until you click on edit.
![aaa](https://user-images.githubusercontent.com/25959809/26948111-10286a4c-4c4a-11e7-9407-23fc939ea7eb.png)
![bbb](https://user-images.githubusercontent.com/25959809/26948110-1026220a-4c4a-11e7-8375-46b279758a63.png)

Submitted by the County Consultants

**Comment by kforderer** [comment]
Role is now visible in show mode-https://www.pivotaltracker.com/story/show/143341023. This item was added to the feedback tracking spreadsheet (it was previously reported as well).
