### ISSUE TITLE
Feedback - "Cross Report"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#36]
9.	Under Cross Report there should not be a field for Agency Name after Department of Justice is checked off?
 
![ccc](https://user-images.githubusercontent.com/25959809/26948265-8dd018be-4c4a-11e7-9e98-5c2c54c95f8c.png)

Submitted by the County Consultants

**Comment by JeffDent** [comment]
I will draft a story to address this change

**Comment by kforderer** [comment]
Placeholder story in icebox. Plan is to auto-populate the cross reporting agencies by county as drop-downs, not free text fields. https://www.pivotaltracker.com/story/show/146178793.
