### ISSUE TITLE
Issue - Unable to Log in 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#37]
Bill Leach is unable to log into Sandbox. 

**Background:**
Bill has been trouble getting onto Sandbox.  He is connecting remotely from his laptop via both VPN and off VPN.    

No success using IE or Chrome.

**Comment by monte-williams** [comment]
@david-sanabria Could you please assist? Thanks!

**Comment by david-sanabria** [comment]
Will contact Bill this afternoon. I will need more info including which VPN client he uses, if he was able to access Sandbox previously, what screen(s) he is able to see, and what errors he is receiving when he tries to connect.

**Comment by monte-williams** [comment]
This has been resolved.
