### ISSUE TITLE
Feedback - Enhancement "Save & Cancel" Buttons [CC]

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#38]
![ss](https://user-images.githubusercontent.com/25959809/27102684-f7e7de8c-503a-11e7-8d14-7e459503fedc.png)
Save and Cancel buttons are too close together. If one intends to press Save but accidentally hits Cancel, all information that was entered in the field is lost. Either move buttons further apart, or suggest a 2nd prompt after pressing Cancel, such as  “are u sure you want to cancel?”

Submitted by the County Consultants

**Comment by JeffDent** [comment]
We will test this further with additional users.
