### ISSUE TITLE
Feedback - Enhancement - "screener narrative automatically populate in the contacts"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#4]
Can we have the screener narrative automatically populate in the contacts, so when we print out the contacts the reason for the referral is included?

Rosanna Fierro, MSW
Social Worker Supervisor II
Yolo County Health & Human Services Agency,

**Comment by JeffDent** [comment]
Interesting. We are not at the point of developing contacts at this point, This information is not really a contact, its an alleged report. We can brainstorm on this idea and see how to incorporate this concept though.

**Comment by JeffDent** [comment]
The revision of what an investigation will look like in NS will give users a clear view of the narrative and contacts. The plan is for the CWS-NS narrative to populate the Screener Narrative in CWS/CMS for now and not into a contact.
