### ISSUE TITLE
Feedback - Allegations: Roles Drop-Down

### ISSUE THREAD

**Issue by MichaelAguilera** [ca-cwds/Sandbox#42]
![allegations](https://user-images.githubusercontent.com/17884360/27446080-1af7b9f4-5731-11e7-8e42-9840e0e8fd1c.png)
It would be useful to have a drop-down menu that allows that user to switch the Alleged Victim and Alleged Perpetrator quickly without requiring the user to scroll back up and manually making the changes in the Person Card.

**Comment by JeffDent** [comment]
We are moving forward with initial design and will monitor feedback on this issue.
