### ISSUE TITLE
Feedback - Allegations: Drop-Down Nested in Allegation Card

### ISSUE THREAD

**Issue by MichaelAguilera** [ca-cwds/Sandbox#44]
![allegationsdropdown](https://user-images.githubusercontent.com/17884360/27446099-3408313a-5731-11e7-896b-149a0650209c.jpg)
The Allegation drop-down menu appears to be nested in the Allegation Card in such a way that the user needs to scroll the card down just to scroll the Allegation list. Please review to improve usability.

**Comment by JeffDent** [comment]
This issue has been resolved. https://www.pivotaltracker.com/story/show/143194557
