### ISSUE TITLE
Feedback - Screening Home Page

### ISSUE THREAD

**Issue by MichaelAguilera** [ca-cwds/Sandbox#46]
We suggest that we add Created Date and Created Time as two additional columns. 
![homescreen](https://user-images.githubusercontent.com/17884360/27446267-c6f6781c-5731-11e7-9439-f2e516a01c55.png)

**Comment by JeffDent** [comment]
Revisions to the index card have been made via https://www.pivotaltracker.com/story/show/149179781, we will look for additional feedback on this topic as users engage with it more.
