### ISSUE TITLE
Feedback - Enhancement - Dashboard

### ISSUE THREAD

**Issue by MichaelAguilera** [ca-cwds/Sandbox#47]
We know that this will be postponed for enhancements but, we would like to see a dashboard for Screeners and Managers to see current screenings/incomplete screenings with alerts.

**Comment by JeffDent** [comment]
https://www.pivotaltracker.com/story/show/146335753 dashboard story for screeners. Supervisors/Managers will have a different dashboard that hasnt been designed yet.
