### ISSUE TITLE
Feedback - HoI Card - Info. Displayed

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#48]
Looks like reporter always show up even when there is no reporter.  I did not identify a reporter on either referral.   No other roles display 
![rp](https://user-images.githubusercontent.com/25959809/27604836-77cf51ee-5b2f-11e7-9c7c-f03acdfe7cce.png)

Guy Trimarchi
Los Angeles

**Comment by JeffDent** [comment]
Reporter is going to show up for now. Reporter concept is being reexamined by UX
