### ISSUE TITLE
Feedback - Enhancement - "Gender"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#5]
The gender drop down menu currently has an option for “other” which I think is kinda derogatory. I get what they are trying to say but I think it’s offensive and for non-binary folks it would likely be triggering.

Joanna La Torre, MSW
Social Worker Practitioner

County of Yolo

**Comment by JeffDent** [comment]
https://www.pivotaltracker.com/story/show/142177199 has all values for gender, including SOGIE that will change the values in the gender field.

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log.  Was reviewed with counties on 6/1/17.
