### ISSUE TITLE
Follow-up and feedback on Previously Submitted Questions

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#51]
Questions we have:
1)	Under communication method, what do you mean by Online 
2)	If we use the calendar, you still cannot enter a time 
3)	With multiple perps, their names seem to run together and you really have to pay attention to each name because of the color under the allegation section
4)	We currently do not have the option to relate clients (minors to parents, etc.)

We are very thankful that there is an update for the perp and client being in the same card. Instead of them populating at the bottom of the referral screen.  Loved it, thanks so much for moving the cards around. We appreciate it. 

There is an easier flow of information being entered and viewed. We also like that a completion box comes up to say that we are finished.  Great work….

Blue Line inside allegation card. I cannot scroll to access the allegations. But if I click into the blue section and try scrolling around, it will eventually begin to show allegation

Nataska Mohair
Maria Lerma
Fresno

**Comment by JeffDent** [comment]
1. Online has been descoped for the moment for legacy parity purposes
2. Calendar and Time should be functional
3. This should be clear now. 
4. adding relationships to new people is being worked on now.
