### ISSUE TITLE
Feedback - Functionality Questions

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#52]
Questions:

1)	For client relations there is only “significant other” would it be possible to have a role of “ex- significant” if two parents are no longer in a relationship or in the process of separating/ divorcing
2)	In the new system : Determine response :  If emailing a Social worker with updated information will it allow to email more than one staff member for example the Sw’s supervisor?  
3)	In the new system child welfare cps hx /snap shot: does it provide the child’s current age or the child’s age at the time of the investigation? Because currently in legacy the child’s age that is displayed  is his or hers current age.  

In regard to CPS history, will the new system show what county the referrals were generated from or will it only give the dates , allegations and outcome?

Maria/Nataska 
Fresno

**Comment by kforderer** [comment]
1. Eventually, we would very much like to include these kinds of relations. Currently limited by CWS/CMS relationship values.   2. Good thought. Next steps are to link it to an existing referral, and then look into potentially emailing the associated workers automatically.  3. That piece of screening doesn't show the children's age yet at all. It's displayed on the child's card, as the Date of Birth. But that's an interesting thought, to show calculated current age, and perhaps to show age at time of a referral in the History. Though that might be confusing to users, to know whether the age they see is current or historic.  History does show the county.
