### ISSUE TITLE
Feedback - Layout/Display - Allegations

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#53]
I was in sandbox/preview today and I created a referral with 3 kids and I noticed a few things that I want to point out.  First when I selected allegations it worked much better than in the past  Was able to select allegations with none of the previous problems    This is how it looks before I saved it
![1](https://user-images.githubusercontent.com/25959809/27606664-fd562a8a-5b35-11e7-8d98-42fdc0c7d92f.jpg)
After saving it it now looks like this
![2](https://user-images.githubusercontent.com/25959809/27606673-0b57b6b2-5b36-11e7-9a51-e987a2d2ebc2.jpg)

My question is why did the view change.  I think the first view is much easier to review that this long list on the second shot..

Guy Trimarchi
Los Angeles

**Comment by JeffDent** [comment]
Guy, we are going with this for the time being to ensure that each allegation is disposed of. We will continue to gather feedback on this issue as we roll this out to core county users and beyond.
