### ISSUE TITLE
Feedback - Layout/Display - HoI

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#54]
In my referral Dario Moore is a perp and as you can see in History card it is displaying a referal where he is the reporting party.  At first it was a tad confusing since I was not used to seeing this but it is cool it shows that thi guy is a reprting party in the other referral.  One suggestion is to have the word “reporter” bolded  In addition, th eroles of the pther people in the referral are not displayed, not sure if in that referral a role was not selected for the others or is it a problem?
![3](https://user-images.githubusercontent.com/25959809/27606763-5baaf142-5b36-11e7-9219-11eb6841e9e1.jpg)

**Comment by kforderer** [comment]
Reporter is being reviewed by UX.
