### ISSUE TITLE
Feedback - Layout/Display - Allegations

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#55]
Good morning, as I am creating a mock screener, I have added multiple allegations per child to each perp. This is visual overload that each time another allegation is added, the system automatically populates the minor and perp again.  Can we have 1 child listed, each perp listed and the multiple allegations listed out on the side, instead of how it appears (shown above) now?

Also, when will the race and language be added to all participants?

Also, as I added more allegations it gets to a point that you cannot see the actual allegations anymore.  You only see a thin blue line (in allegations) and fortunately I knew to click in the blue area to find the remainder of allegations. 
![4](https://user-images.githubusercontent.com/25959809/27606859-ae50c19c-5b36-11e7-8bef-bba0a6993492.jpg)

Thanks ,

Nataska Mohair
Fresno

**Comment by kforderer** [comment]
Display of allegations is designed for disposition by allegation. Would like to revisit different views for screener and investigator in the future.  Stories to add race/ethnicity: https://www.pivotaltracker.com/story/show/138532575 and https://www.pivotaltracker.com/story/show/138532695
