### ISSUE TITLE
Feedback - Funtionality/Layout/Display - Mobile Devices (CC)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#56]
**Calendar**
•	Calendar function not working in mobile. User cannot select the calendar drop down. Drop down carrot seems to be too small.

**Screening Global**
•	No log out option available
•	The log in screen is not formatted correctly for mobile
1. User only sees the Notice when loading the URL
2. User needs to scroll down to get to log in fields
3. Log in fields are too small to see text

•	Font size, bold and color need to be enhanced for better visibility
•	Home and Edit buttons come up as only hyperlinks and not buttons at the bottom of the page

**Person Search**
•	When results populate for person search, the majority of the screen is enveloped by the person’s image
1. Please consider removing the image and move to a link or pop-up
2. If not, please shrink the image
3. Consider moving the name above image

**Allegations**
•	Cannot scroll or select allegations at all

Submitted by the County Consultants

**Comment by JeffDent** [comment]
Bug story created https://www.pivotaltracker.com/story/show/148265503
