### ISSUE TITLE
Feedback - Page Functionality (CC)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#59]
•	No log out option available
•	Home and Edit buttons come up as only hyperlinks and not buttons at the bottom of the page

Submitted by the County Consultants

**Comment by JeffDent** [comment]
We will have a discussion with TPT on the logout issue. The home and edit buttons will disappear soon.

**Comment by JeffDent** [comment]
User Story https://www.pivotaltracker.com/story/show/150069596 will address this
