### ISSUE TITLE
Feedback - Enhancement - "Locations"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#6]
I was thinking that it would be good to be able to “check-in” places like schools or residences so that we don’t have to type the address every time we go somewhere.

Joanna La Torre, MSW
Social Worker Practitioner
County of Yolo

**Comment by JeffDent** [comment]
Interesting. I will share with UX team to see how this may work with address validation efforts/GIS

**Comment by kforderer** [comment]
UX story in the icebox to explore this. Would depend on prioritization from Product Owner.  https://www.pivotaltracker.com/story/show/139964671.
