### ISSUE TITLE
Feedback - Editing Roles and Allegations 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#61]
I was creating a referral and I created a vic, a perp and a reporter   I saved the card and realized I got the perp and reporter mixed up.  So I changed their roles and when I saved the card again in the allegation field there was nothing displayed.  It was displayed the first time I saved.  Then I finally clicked on the pencil in the allegation card and then the perp and vic appeared in the allegation card. Then selected the allegations and saved.  Don’t understand why I had to click on the pencil in the allegation field when I already made the changes in the role fields and saved the changes.  Why wouldn’t that change field appear in the allegation field right away.

Guy Trimarchi
Los Angeles

**Comment by JeffDent** [comment]
We are looking at splitting out the reporter from the group to alleviate confusion on this issue. 
Second, when changes are made to fields with dependencies like roles to allegations, then you have to edit the card to see the changes take place. This is something we can keep an eye on for the future. Here is the link to the UX story to re-examine reporterhttps://www.pivotaltracker.com/story/show/148040455
