### ISSUE TITLE
Feedback - Roles - Reporting Party 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#62]
After reviewing  https://github.com/ca-cwds/Sandbox/issues/61  I would add as a suggestion that the Reporter have it's own card separate from the card the current card layout. I could see where there is lots of room for error in assigning "roles" causing the user to need to constantly review, or slow their process, in order to make sure that the people aren't mixed up. 

Based upon my own experience at a Hotline, I could see this slowing me down and I'm fairly system suave. But if the chance of its occurrence was removed, I could use that focus on other required task. I would be one less thing to have to double check.  

https://github.com/ca-cwds/Sandbox/issues/61

Monte Williams
County Consultant

**Comment by monte-williams** [comment]
1)	It would be preferable to have the reporter (mandated/non-mandated) to have their own card. That way information is clear, we know exactly who to call and exactly what their role is.  Currently, all parties listed in the new system all run together.  We cannot differentiate the perp from the RP
2)	Aside from having a separate card, there needs to be a drop down box of options that clearly identify who the RP is.  Currently in legacy there is a generic drop down that doesn’t provide clarity about the RP’s role in relation to the referral.  In legacy it says relative (would like to identify exactly who), it also says school personnel (but who are we referring to), etc.

3)	Once we enter (add) RP information, is it saved only for that referral or is it saved in the system because the RP’s typically call back to make additional referrals

4)	RP address information: although it does list address type, can we be more specific. If it’s a school, what school.  We need to be able to add specific information. As a hotline worker and responder, I would want to see clear information that is easily accessible.  






Nataska Mohair
Fresno County

**Comment by JeffDent** [comment]
We are re-looking at this issue based on this feedback. Here is the link to the UX story to re-examine
https://www.pivotaltracker.com/story/show/148040455
