### ISSUE TITLE
Enchancement - Person Card - Role Drop Down

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#63]
Could the role drop-down close once a selection is made instead staying open as it currently does, until clicking elsewhere on the page?

![personcard](https://user-images.githubusercontent.com/25959809/28293724-71431cb2-6b0a-11e7-8f50-25ee24d39d15.jpg)

Monte Williams
Country Consultant

**Comment by JeffDent** [comment]
User Story https://www.pivotaltracker.com/story/show/150069430 will address all multi select dropdown fields to alleviate this issue.
