### ISSUE TITLE
Enhancement - Search - Creating New Person

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#64]
When searching a person (example Carl Smith) and that person does not exist, when you click "Create a New Person" it would be nice if "Carl Smith" was automatically entered into the name fields. 

Monte Williams

**Comment by kforderer** [comment]
UX explored this, but legacy needs the name parsed between first, middle, last, and the new system wouldn't know from what the user typed how to parse it (is this string of letters a first name? a last name? Does the space mean that it's FN LN or LN FN?) Could be done, but low on priorities
