### ISSUE TITLE
Feedback - Functionality - "Undo/Redo"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#66]
Something I have noticed is there is not an undo or redo button.     I think this would be very helpful, especially for typing in the narrative fields.  Additionally, if we accidentally click on the “x” and cancel/delete something we have created a card, it would be helpful to be able to have an undo button to correct that so that we don’t have to start over entering information for that card.  Without this feature, I think we are creating a pain point for the new system.

Wendy Vazquez, 
Butte County

**Comment by kforderer** [comment]
Plan to add alerts for the people cards which can be X'd out (https://www.pivotaltracker.com/story/show/139823053)
