### ISSUE TITLE
Feedback - HoI Card 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#67]
Legacy has a way to show both referral and case history for the entire family on an individual's client notebook. Currently NS will only show the individual's history as they are added to the screening. 

Having the related family member's history come up when I search an individual is very helpful when a reporting party has limited information on the family. In Legacy if I find one person, I potentially find them all. With NS it seems it will take more effort, thus more time, to find the other family members that were not provided by the reporting party.  The lack of this information could lead to incomplete assessment, miss-assessment of response base upon age of unidentified children, add work to the investigating social worker who has to add the missing members and more. 

Here is a mock up I did to possibly resolve this issue:
![hoi v1 1](https://user-images.githubusercontent.com/25959809/28628371-5432e4c4-71d9-11e7-88d9-560503e344e4.png)

Here is a screenshot of how the information is provided in Legacy:
![leg hoi](https://user-images.githubusercontent.com/25959809/28629490-6bb2f7a8-71dc-11e7-9ded-3f9e5f75b7c3.png)

Monte Williams

**Comment by kforderer** [comment]
UX has a story to explore how to highlight related people in search and potentially add related people as a group. Who entered this comment? We can make sure to reach out when designing this.
