### ISSUE TITLE
Feedback - Unidentified Perpetrator 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#69]
NS the way it is currently designed and functioning could cause the Screener to do **more** work than Legacy does for the exact same function. NS currently **REQUIRES** that a person be marked as the perpetrator in order to be able to input the allegations on a person that has to be marked victim. If the perpetrator is "unknown", then an "Unknown Person" needs to be created in NS in order to proceed. 

In Legacy, a perpetrator does not need to be added or attached  (see below) to the referral in order to be able to enter allegations for the child. NS is currently adding this step. 

![perp](https://user-images.githubusercontent.com/25959809/28695174-8b784384-72e2-11e7-89f5-85d8b3c198be.png)

**Comment by JeffDent** [comment]
User Story https://www.pivotaltracker.com/story/show/150069150 has been drafted to address this issue.
