### ISSUE TITLE
Feedback - "Correction/Typo" - Language Drop-down

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#7]
on the new system and noticed that Ilocano is misspelled in the language drop-down menu (they have it as Ilacano….)

Joanna La Torre, MSW
Social Worker Practitioner
County of Yolo

**Comment by JeffDent** [comment]
@lzinky can we double check this value in legacy to make sure that we didnt include a typo?

**Comment by lzinky** [comment]
@JeffDent The value as it appears in the CWS/CMS Code xTools code table is: Ilacano.  This is incorrect as they noted at it should be "Ilocano".  Both CWS and CWS-NS need to be corrected.

**Comment by JeffDent** [comment]
https://www.pivotaltracker.com/story/show/145161837 to fix this.
