### ISSUE TITLE
Question - Capability - Audit

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#70]
What are the audit capabilities for NS? For instance, the referral gets approved and data is sent to legacy. However, the hotline user goes in and updates information after approval. Is there a way in NS to track the updates made? 

Katie Hastings 
Implementation Lead – Los Angeles

**Comment by JeffDent** [comment]
Logging and auditing functions are being looked at and will be in a forthcoming PI. 
As far as your scenario, we will not allow the screening to be modified once it has been approved. (Future work_supervisor approval)
