### ISSUE TITLE
Question - Notification between Legacy and NS

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#71]
1.	Does the investigations worker in legacy get notified of the changes made in NS? 

2.	And what about changes to the referral data in legacy? Will those be reflected in NS? If so, will those changes override existing data or will it appear as an append? 

Katie Hastings
Implementation Lead – Los Angeles

**Comment by JeffDent** [comment]
Katie, 
1. No notifications are coming from NS to alert CWS/CMS  (or vice versa) users of any changes at the moment. That will be a future enhancement.
