### ISSUE TITLE
Issue - Unable to Log-in into Sandbox

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#73]
I was trying to log on to preview AKA sandbox and I get  “Invalid login credentials”    I went to sandbox.cwds.ca.gov

Guy Trimarchi
Los Angeles

**Comment by monte-williams** [comment]
I am also receiving the same error message when trying to log in.

Monte Williams

**Comment by monte-williams** [comment]
@david-sanabria

**Comment by speddi01** [comment]
@monte-williams  It Seems you are using the you are using the wrong password for the user ID : monte.williams@osi.ca.gov, please let me know I can send you the password

**Comment by speddi01** [comment]
@monte-williams Invalid credentials attempt : trimag@dcfs.lacounty.gov also , let me know if you want I can send the passwords over

**Comment by monte-williams** [comment]
@speddi01 could you please send the passwords. Thank you

**Comment by speddi01** [comment]
@monte-williams Sent the login detils  over to respective emails.

**Comment by monte-williams** [comment]
@speddi01  Thank you. I received and tried the credentials from the email and I get the same error message.

**Comment by speddi01** [comment]
![screen shot 2017-08-08 at 2 05 05 pm](https://user-images.githubusercontent.com/29740700/29094589-b788d902-7c42-11e7-93b5-a7ed83d714d3.png)


Able to login with the same user id and password

**Comment by monte-williams** [comment]
[lg.docx](https://github.com/ca-cwds/Sandbox/files/1209588/lg.docx)
Just tried it again. Once through the VPN, and once through my County portal.

**Comment by speddi01** [comment]
IT must be a space when you are typing or pasting the password if not this may be browser cache issue , please clear browser history and cache or use other browser and try again.

**Comment by monte-williams** [comment]
That was it! There was a space when I copy/paste. Thanks @speddi01

**Comment by monte-williams** [comment]
This issues has been resolved
