### ISSUE TITLE
Question - County Specific Templates

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#74]
I have an action item to report back and provide assurances that counties will retain in NS their ability to upload and customize county specific templates.  I need to be able to reference a user story as proof.  It can be in the backlog - that's fine.  But I cannot find a user story to that effect in your backlog, and I'm thinking that's where it should be.  
 
Has there been any discussion of this?  Any thoughts that perhaps Intake is not the right place to look?  If not, where?  I would appreciate any thoughts you might have.
 
Penny Liles
CWDA Consultant

**Comment by JeffDent** [comment]
This question speaks to the larger issue of Document Management, for which we dont have an identified solution for at the moment. We are aware of county templates and the need to upload and customize these documents. We just dont have a solution for this issue at the moment.
