### ISSUE TITLE
Question - Functionality - Narrative (NS to Legacy) (CC)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#77]
In those instances where a Screening becomes a Referral in CWS- NS, I wanted to make sure the narrative input into CWS- NS will actually populate back into CWS/CMS.  There is no narrative field in CWS/CMS- in CWS/CMS, the screener inputs the narrative into the Screener Narrative document they have to generate.  Will this Screener Narrative document be automatically generated in CWS/CMS and the CWS- NS narrative text populate into it once a screening becomes a referral in CWS- NS?

Bill Leach
County Consultant

**Comment by JeffDent** [comment]
We are starting first with the automatic generation of the Screener Narrative Doc as a litmus test to leverage content in CWS-NS to generate Word docs in CWS/CMS. We are working towards automatically generating the docs, but it will be manual generation until then.
