### ISSUE TITLE
Question - Emergency Response Document (NS to Legacy) [CC]

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#78]
In those instances where a Screening becomes a Referral in CWS- NS, I wanted to make sure they keep in mind the Emergency Response Referral Document (ERRD) that is required in order to close all but E/O referrals in CWS/CMS. The ERRD is very similar to what is being referred to as Snapshot or the Client History section of the Screening page. Will the ERRD be automatically generated in CWS/CMS once a screening becomes a referral in CWS- NS?

Bill Leach 
County Counsultant

**Comment by JeffDent** [comment]
We are starting first with the automatic generation of the Screener Narrative Doc as a litmus test to leverage content in CWS-NS to generate Word docs in CWS/CMS. We are working towards automatically generating the docs, but it will be manual generation until then.
