### ISSUE TITLE
Feeback - Saving and Possible Auto-Save 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#79]
The first was a concern about having to save each individual card, because as a user, I would assume if I click “Save” on a screening that it would be saving all of the changes that I made on the entire screening, not just the section for that card.  If I happen overlook a “Save” button in a particular section, then had to walk away from my screening or got interrupted before I was able to submit, I might lose valuable information I entered.  

The second was the suggestion from one of our group for a regular “Auto-Save” feature so if I am not great at saving and I suddenly lose power, or get an urgent phone call, etc., I will not lose ALL of my work.

Thanks!

Jennifer Snarr
County Consultant

**Comment by JeffDent** [comment]
At this time we are moving forward with the save pattern in place for exactly the reasons you are mentioning. We want users to save frequently, so they dont lose large pieces of work. We will continue to monitor feedback on this issue as further feedback comes in.
