### ISSUE TITLE
Feedback - Search - "Ordering"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#8]
I am curious why (or the reasoning) behind the order of search results. As you can see, the name [name deleted], there were 8 results that came back before a [name deleted] (not the one I was searching for) appeared. It was 21 before a second [name deleted] appeared (still not the one), 39 before a third appeared and 45 before the client appeared. However if the beginning of the SSA was typed then he appeared but not in order (see fig 2).
 

Will Dayton,
Administrative Services Analyst,
Yolo County CWS/CMS Coordinator,

**Comment by kforderer** [comment]
Closing because added to Intake Team Feedback and Question log.  Was reviewed with counties on 6/1/17.  There are currently many stories to improve the Search logic (and order of appearance).  See the Epic in Pivotal Tracker: EPIC: https://www.pivotaltracker.com/epic/show/2723493
