### ISSUE TITLE
Issue - Allegations - "Unable to assign"

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/Sandbox#9]
Once I had a minor and a parent I identified their roles victim and perp but when I went to create allegations I could not 

![allegations](https://cloud.githubusercontent.com/assets/25959809/25594369/0cbf41e8-2e75-11e7-8fad-a17eb0e8a1cd.png)

Guy Trimarchi, CSA III
Los Angeles DCFS

**Comment by JeffDent** [comment]
This issue has been addressed. A user can add a victim and perp and the allegations card will become active.
